# Generated by Django 4.2.29 on 2026-03-05 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('set_name', models.CharField(choices=[('A', 'Set A'), ('B', 'Set B'), ('C', 'Set C')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('total_questions', models.IntegerField(default=30)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('easy_percentage', models.IntegerField(default=40)),
                ('medium_percentage', models.IntegerField(default=40)),
                ('hard_percentage', models.IntegerField(default=20)),
                ('easy_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('hard_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('published', 'Published')], default='generated', max_length=20)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=180)),
                ('instructions', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper_group_id', models.CharField(blank=True, help_text='Groups related A/B/C sets', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='courses.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Generated Paper',
                'verbose_name_plural': 'Generated Papers',
                'db_table': 'dj_generated_papers',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.generatedpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_appearances', to='questions.question')),
            ],
            options={
                'db_table': 'dj_paper_questions',
                'ordering': ['question_number'],
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
