# Generated by Django 4.2.29 on 2026-03-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False, 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'managed': False, 'verbose_name': 'Question Category', 'verbose_name_plural': 'Question Categories'},
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
