# Generated by Cascade on 2026-03-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_examblueprint_paper_type'),
        ('questions', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='questions',
                to='departments.department',
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='questions',
                to='departments.subject',
            ),
        ),
    ]
