# Generated by Django 4.2.16 on 2026-03-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
