# Generated by Django 4.2.16 on 2026-03-12 12:14

from django.db import migrations, models


def drop_tags_column_if_exists(apps, schema_editor):
    table_name = 'dj_questions'
    column_name = 'tags'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND COLUMN_NAME = %s
            """,
            [table_name, column_name],
        )
        exists = cursor.fetchone()[0]
        if exists:
            cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{column_name}`")


def add_answer_data_column_if_missing(apps, schema_editor):
    table_name = 'dj_questions'
    column_name = 'answer_data'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND COLUMN_NAME = %s
            """,
            [table_name, column_name],
        )
        exists = cursor.fetchone()[0]
        if not exists:
            cursor.execute(
                f"ALTER TABLE `{table_name}` ADD COLUMN `{column_name}` JSON NOT NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_add_department_subject_to_questions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_tags_column_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='question',
                    name='tags',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_answer_data_column_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='question',
                    name='answer_data',
                    field=models.JSONField(blank=True, db_column='answer_data', default=list),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='difficulty',
                    field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='moodle_question_id',
                    field=models.BigIntegerField(blank=True, null=True, unique=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='question_text',
                    field=models.TextField(db_column='text'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='question_type',
                    field=models.CharField(choices=[('mcq', 'MCQ'), ('descriptive', 'Descriptive'), ('multichoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('essay', 'Essay'), ('numerical', 'Numerical'), ('matching', 'Matching'), ('calculated', 'Calculated')], max_length=64),
                ),
            ],
        ),
    ]
