# Generated by Django 4.2.29 on 2026-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_quiz_options'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examblueprint',
            options={'ordering': ['department', 'category__order', 'course__course_code', 'subject__name'], 'verbose_name': 'Exam Blueprint', 'verbose_name_plural': 'Exam Blueprints'},
        ),
        migrations.RemoveConstraint(
            model_name='examblueprint',
            name='unique_blueprint',
        ),
        migrations.RemoveConstraint(
            model_name='examcategory',
            name='unique_dept_category',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_course_dept_subject',
        ),
        migrations.AlterField(
            model_name='blueprintpapergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='descriptive_count',
            field=models.PositiveIntegerField(default=6, help_text='Number of descriptive/essay questions per paper'),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='descriptive_marks',
            field=models.PositiveIntegerField(default=10, help_text='Marks awarded per descriptive question'),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='instructions',
            field=models.TextField(blank=True, default='1. Read all questions carefully before answering.\n2. Section A — Attempt ALL objective questions.\n3. Section B — Attempt any 6 descriptive questions.\n4. Marks are shown alongside each question.\n5. Mobile phones and electronic devices are NOT permitted.'),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='mcq_count',
            field=models.PositiveIntegerField(default=40, help_text='Number of MCQ/Objective questions per paper'),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='mcq_marks',
            field=models.PositiveIntegerField(default=1, help_text='Marks awarded per MCQ question'),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display sort order (lower = first)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='examblueprint',
            unique_together={('department', 'category', 'course', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='examcategory',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('course', 'department', 'name')},
        ),
    ]
