# Generated by Django 4.2.29 on 2026-03-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_examblueprint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprintpapergroup',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterModelOptions(
            name='examblueprint',
            options={'ordering': ['department', 'category__order', 'course__course_code', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='examcategory',
            options={'ordering': ['department', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short code e.g. COMM, MECH, ELEC', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='color_hex',
            field=models.CharField(default='#0ea5e9', help_text='Accent colour for UI', max_length=7),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='descriptive_count',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='descriptive_marks',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='mcq_count',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='mcq_marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
    ]
