# Generated by Cascade on 2026-03-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_blueprintpapergroup_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examblueprint',
            unique_together={
                (
                    'department',
                    'category',
                    'course',
                    'subject',
                    'mcq_count',
                    'mcq_marks',
                    'descriptive_count',
                    'descriptive_marks',
                )
            },
        ),
    ]
