# Generated by Cascade on 2026-03-12

from django.db import migrations


def seed_engineering(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    ExamCategory = apps.get_model('departments', 'ExamCategory')

    dept, _ = Department.objects.get_or_create(
        code='ENGG',
        defaults={
            'name': 'Engineering',
            'description': '',
            'color_hex': '#0ea5e9',
            'is_active': True,
        }
    )

    if not dept.is_active:
        dept.is_active = True
        dept.save(update_fields=['is_active'])

    defaults = [
        ('Initial', 0),
        ('Promotion', 1),
        ('Refresher', 2),
    ]

    for name, order in defaults:
        cat, created = ExamCategory.objects.get_or_create(
            department_id=dept.id,
            name=name,
            defaults={
                'order': order,
                'description': '',
                'is_active': True,
            }
        )
        if not created and not cat.is_active:
            cat.is_active = True
            cat.save(update_fields=['is_active'])


def unseed_engineering(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    ExamCategory = apps.get_model('departments', 'ExamCategory')

    dept = Department.objects.filter(code='ENGG').first()
    if not dept:
        return

    ExamCategory.objects.filter(department_id=dept.id).update(is_active=False)
    dept.is_active = False
    dept.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_examblueprint_unique_together'),
    ]

    operations = [
        migrations.RunPython(seed_engineering, reverse_code=unseed_engineering),
    ]
