# Generated by Cascade on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_seed_engineering_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='examblueprint',
            name='paper_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='examblueprint',
            unique_together={
                (
                    'department',
                    'category',
                    'course',
                    'subject',
                    'paper_type',
                    'mcq_count',
                    'mcq_marks',
                    'descriptive_count',
                    'descriptive_marks',
                )
            },
        ),
    ]
