# Generated by Cascade on 2026-03-12

from django.db import migrations
from django.utils import timezone


def seed_engineering_excel(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    ExamCategory = apps.get_model('departments', 'ExamCategory')
    Subject = apps.get_model('departments', 'Subject')
    ExamBlueprint = apps.get_model('departments', 'ExamBlueprint')
    connection = schema_editor.connection

    dept = Department.objects.filter(code='ENGG').first()
    if not dept:
        return

    def cat(name):
        return ExamCategory.objects.filter(department_id=dept.id, name=name).first()

    cat_initial = cat('Initial')
    cat_refresher = cat('Refresher')
    if not cat_initial or not cat_refresher:
        return

    # Seed Engineering courses (from Excel)
    courses = [
        ('JE/SSE/Works', 'JE/SSE/Works', 'Engineering'),
        ('IE/SSF/Works', 'IE/SSF/Works', 'Engineering'),
    ]

    course_map = {}
    for code, name, department_name in courses:
        with connection.cursor() as cursor:
            cursor.execute("SELECT id FROM dj_courses WHERE code = %s LIMIT 1", [code])
            row = cursor.fetchone()
            if row:
                course_id = row[0]
            else:
                now = timezone.now()
                cursor.execute(
                    """
                    INSERT INTO dj_courses
                        (code, name, department, trms_course_id, moodle_course_id, is_active, created_at, updated_at)
                    VALUES
                        (%s, %s, %s, NULL, NULL, %s, %s, %s)
                    """,
                    [code, name, department_name, True, now, now],
                )
                course_id = cursor.lastrowid

        course_map[code] = course_id

    # Seed Subjects seen in Excel
    subjects = [
        ('JE/SSE/Works', 'ENGINEERING'),
        ('JE/SSE/Works', 'ENGINEERING+MISC'),
        ('JE/SSE/Works', 'MISC'),
        ('IE/SSF/Works', 'MISC.COMBINED'),
    ]

    subject_map = {}
    for course_code, subj_name in subjects:
        course_id = course_map[course_code]
        s = Subject.objects.filter(course_id=course_id, department_id=dept.id, name=subj_name).first()
        if not s:
            s = Subject.objects.create(
                course_id=course_id,
                department_id=dept.id,
                name=subj_name,
                code='',
                description='',
                is_active=True,
            )
        subject_map[(course_code, subj_name)] = s

    # Helper: make blueprint if absent
    def ensure_blueprint(category, course_code, subject_name, paper_type, mcq_count, mcq_marks, desc_count, desc_marks):
        course_id = course_map[course_code]
        s = subject_map[(course_code, subject_name)]
        exists = ExamBlueprint.objects.filter(
            department_id=dept.id,
            category_id=category.id,
            course_id=course_id,
            subject_id=s.id,
            paper_type=paper_type,
            mcq_count=mcq_count,
            mcq_marks=mcq_marks,
            descriptive_count=desc_count,
            descriptive_marks=desc_marks,
            is_active=True,
        ).order_by('id').first()
        if exists:
            return
        ExamBlueprint.objects.create(
            department_id=dept.id,
            category_id=category.id,
            course_id=course_id,
            subject_id=s.id,
            paper_type=paper_type,
            mcq_count=mcq_count,
            mcq_marks=mcq_marks,
            descriptive_count=desc_count,
            descriptive_marks=desc_marks,
            duration_minutes=180,
            instructions='',
            is_active=True,
        )

    # Excel mapping (ignoring viva)
    # INITIAL: JE/SSE/Works
    ensure_blueprint(cat_initial, 'JE/SSE/Works', 'ENGINEERING', 'First Visit', 40, 1, 6, 10)          # 40 + 60
    ensure_blueprint(cat_initial, 'JE/SSE/Works', 'ENGINEERING+MISC', 'Second Visit', 40, 1, 6, 10)   # 40 + 60

    # Subjective=45; keep count integer and allow marks to vary => 3 x 15
    ensure_blueprint(cat_initial, 'JE/SSE/Works', 'ENGINEERING', 'Third Visit', 30, 1, 3, 15)         # 30 + 45
    ensure_blueprint(cat_initial, 'JE/SSE/Works', 'MISC', 'Third Visit', 30, 1, 3, 15)                # 30 + 45

    # REFRESHER: IE/SSF/Works
    ensure_blueprint(cat_refresher, 'IE/SSF/Works', 'MISC.COMBINED', 'Only One Visit', 80, 1, 2, 10)  # 80 + 20


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_examblueprint_paper_type'),
    ]

    operations = [
        migrations.RunPython(seed_engineering_excel, reverse_code=migrations.RunPython.noop),
    ]
